### ISSUE TITLE
Zeros in --pixy_mode

### ISSUE THREAD

**Issue by ksamuk** [RILAB/mop#4]
Hey Silas! 

Just working on getting pixy integration up and running. --pixy_mode is working great! Just a quick idea: I don't think we'll ever need to write out the sites with 0 individuals passing filter. Saves a bit of space as well (~15% smaller file in my tests).

I think something like this would basically do the trick:

```
def pixy_printer(chrom, start, end, n_ind):
    if n_ind > 0:
        if start > 0 and  end > 0:
            print(f"{chrom}\t{start-1}\t{end}\t{n_ind}")
```

Thanks for making this awesome tool!

**Comment by silastittes** [comment]
Thanks for this suggestion, Kieran. The edit works as expected. Pushed the changes and updated pip (version 0.0.5).
Awesome to hear mop + pixy is working!
