### ISSUE TITLE
0 vs 1 Indexing

### ISSUE THREAD

**Issue by ksamuk** [RILAB/mop#5]
Hi Silas!

Sorry to bug you again. Quick sanity check re: mop output. If one is working with 1-indexing, do you think it is OK to just drop the second column for single-site output? 

e.g. 

```
X       0       1       36
X       1       2       36
X       2       3       36
X       3       4       36
X       4       5       36
```

The '36' applies to the first base of the X chromosome in this case? Thanks for your help!

**Comment by ksamuk** [comment]
Follow-up, if I am understanding this correctly, the pixy output could be even more compact if the second column was always dropped, since pixy uses 1-based indexing for everything:

```
def pixy_printer(chrom, start, end, n_ind):
            if n_ind > 0:
                if start > 0 and  end > 0:
                    print(f"{chrom}\t{end}\t{n_ind}")
```

I realize this would mean those output files would no longer be real BED files, but maybe worth it for the size reduction?

Let me know what you think!

**Comment by silastittes** [comment]
No need to apologize, I'm really excited this is happening! 
You are thinking about the format right, and I agree this seems good for pixy_mode. Gonna keep the original bed format for the non pixy_mode so I don't break any of my or other folks' existing pipeline. Update made! (v0.0.6)
